### ISSUE TITLE
Zmena certifikacni autority

### ISSUE THREAD

**Issue by Rohlik** [l-ra/openeet-shell#3]
Byla provedena razantni zmena v certifikacni autorite dle http://www.etrzby.cz/cs/oznameni-k-testovacimu-prostredi-playground a tudiz od 6.1.2017 jiz nelze pouzit certifikaty, ktere mas v tomto GITu.

Nechces certifikaty aktualizovat?

**Comment by l-ra** [comment]
Hotovo v 0d0444aef6

**Comment by Rohlik** [comment]
Díky.
